djangoApp/urls.py
from django.urls import path, include
from .import views
from.views import serve_presigned_media
urlpatterns = [
        path('media/<path:file_key>/', serve_presigned_media, name='serve_presigned_media'),
        path('', views.home, name = 'home'),
        path('home/', views.home, name = 'home'),
        path('trainingjournal/', views.trainingjournal, name='trainingjournal'),
        path('techniquelibrary/', views.techniquelibrary, name='techniquelibrary'),
        path('loginpage/', views.loginpage, name = 'loginpage'),
        path('logoutuser/', views.logoutuser, name= 'logoutuser'),
        path('registerpage/', views.registerpage, name='registerpage'),
        path('journalform/', views.journalform, name='journalform'),
        path('techniqueform/', views.techniqueform, name='techniqueform'),
        path('updatejournal/<str:pk>/', views.updatejournal, name='updatejournal'),
        path('updatetechnique/<str:pk>/', views.updatetechnique, name='updatetechnique'),
        path('deletejournal/<str:pk>/', views.deletejournal, name='deletejournal'),
        path('deletetechnique/<str:pk>/', views.deletetechnique, name='deletetechnique'),
        path('techniqueseries/', views.techniqueseries, name ='techniqueseries'),
        path('techniqueseriesform/', views.techniqueseriesform, name= 'techniqueseriesform'),
        path('updatetechniqueseries/<str:pk>/', views.updatetechniqueseries, name= 'updatetechniqueseries'),
        path('deletetechniqueseries/<str:pk>/', views.deletetechniqueseries, name= 'deletetechniqueseries'),
        path('stats/', views.stats, name='stats')
]

djangoProject/urls.py
from django.urls import path
from djangoApp import views
"""
URL configuration for djangoProject project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('djangoApp.urls')),
    path('serve-media/<path:file_key>/', views.serve_presigned_media, name='serve_presigned_media'),
]

djangoApp/models.py
#models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class TrainingLogEntry(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Date_Added = models.DateTimeField(auto_now_add=True, null=True)
    Training_Date=models.DateField(null=True)
    Techniques = models.CharField(max_length=100, null=True)
    Notes=models.TextField(blank=True, null=True)
    Duration = models.IntegerField(null=True, blank=True, help_text="Minutes")
    image = models.ImageField(upload_to='training_log_images/', blank=True, null=True)
    video = models.FileField(upload_to='training_log_videos/', blank=True, null=True)  # Video field added
    def __str__(self):
        return self.Training_Date.strftime('%Y-%m-%d') if self.Training_Date else 'Unknown Training Date'

class TechniqueLibraryEntry(models.Model):
    STATUS = (
        ('Needs Improvement', 'Needs Improvement'),
        ('Proficient', 'Proficient'),
        ('Mastered', 'Mastered'),
    )
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Technique_Name = models.CharField(max_length=200, null=True)
    Description = models.TextField(blank=True, null=True)
    Date_Added = models.DateTimeField(auto_now_add=True, null=True)
    Status = models.CharField(max_length=200, null=True, choices=STATUS)
    image = models.ImageField(upload_to='technique_library_images/', blank=True, null=True)
    video = models.FileField(upload_to='technique_library_videos/', blank=True, null=True)
    def __str__(self):
        return self.Technique_Name

class TechniqueSeriesEntry(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    SeriesName = models.CharField(max_length=200, null=True)
    Description = models.TextField(blank=True, null=True)
    Techniques = models.ManyToManyField(
        'TechniqueLibraryEntry',
        through='TechniqueSeriesLinking',  
        blank=True
    )
    def __str__(self):
        return self.SeriesName
    

class TechniqueSeriesLinking(models.Model):
    TechniqueSeriesEntry = models.ForeignKey('TechniqueSeriesEntry', on_delete=models.CASCADE)
    TechniqueLibraryEntry = models.ForeignKey('TechniqueLibraryEntry', on_delete=models.CASCADE)
    order = models.PositiveIntegerField(default=0)
    class Meta:
        ordering = ['order']
        unique_together = ('TechniqueSeriesEntry', 'TechniqueLibraryEntry')

    

djangoApp/views.py
#views.py
from itertools import count
import boto3
from django.db.models import Sum, Count
from django.conf import settings
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from .filters import *
import logging
from django.core.cache import cache

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')



# Create your views here.
@login_required
def serve_presigned_media(request, file_key):
    if not file_key.startswith('media/'):
        file_key = f'media/{file_key}'
    logging.debug(f'Received file key: {file_key}')
    print("Generating pre-signed URL for key:", file_key)
    """Serve a pre-signed URL for authenticated users."""
    cache_key = f'presigned_url_{file_key}'
    presigned_url = cache.get(cache_key)

    if not presigned_url:
       
      s3_client = boto3.client('s3', 
                              region_name=settings.AWS_S3_REGION_NAME,
                              aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                              aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY
      )
    
      try:
         presigned_url = s3_client.generate_presigned_url('get_object',
                                                         Params={'Bucket': settings.AWS_STORAGE_BUCKET_NAME,
                                                                 'Key': file_key},
                                                         ExpiresIn=3600)
         cache.set(cache_key, presigned_url, timeout=3500) 
         logging.debug(f'Generated presigned URL: {presigned_url}')
      except Exception as e:
        logging.error(f'Error generating presigned URL: {e}')
        # Log the error
        raise Http404("Error generating URL")

    # Redirect to the pre-signed URL
    return redirect(presigned_url)

def home(request):
   return render(request,'djangoApp/home.html')

@login_required(login_url='loginpage')
def trainingjournal(request):
   current_user= request.user
   journalentry = TrainingLogEntry.objects.filter(user=current_user).order_by('-Training_Date')
   jFilter = TrainingLogFilter(request.GET, queryset=journalentry)
   journalentry= jFilter.qs
   context = {'jFilter': jFilter, 'journalentry':journalentry}
   return render(request, 'djangoApp/trainingjournal.html', context) 

@login_required(login_url='loginpage')
def techniquelibrary(request):
   current_user=request.user
   techniqueentry = TechniqueLibraryEntry.objects.filter(user=current_user).order_by('Technique_Name')
   tFilter = TechniqueLibraryFilter(request.GET, queryset=techniqueentry)
   techniqueentry = tFilter.qs
   context = {'tFilter': tFilter, 'techniqueentry': techniqueentry}
   return render(request, 'djangoApp/techniquelibrary.html', context)

def loginpage(request):
   if request.user.is_authenticated:
      return redirect('home')
   else:

      if request.method == 'POST':
         username = request.POST.get('username')
         password = request.POST.get('password')
         user= authenticate(request, username=username, password=password)
         if user is not None:
            login(request, user)
            return redirect('home')
         else:
            messages.info(request,'Username or Password is incorrect.')
            
      context = {} 
      return render(request,'djangoApp/loginpage.html', context)

def logoutuser(request):
   logout(request)
   return redirect ('loginpage')

def registerpage(request):
   if request.user.is_authenticated:
      return redirect('home')
   else:
      form = CreateUserForm()
      if request.method == 'POST':
         form = CreateUserForm(request.POST)
         if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect ('loginpage')

      context = {'form':form}
      return render(request, 'djangoApp/registerpage.html', context)
   
@login_required(login_url='loginpage')
def journalform(request):
   form = JournalForm()
   if request.method== 'POST':
      form= JournalForm(request.POST, request.FILES, user=request.user)
      if form.is_valid():
         form.save()
         return redirect('trainingjournal')
   else:
      form =JournalForm(user=request.user)
   context = {'jform': form }
   return render(request, 'djangoApp/journalform.html', context)

@login_required(login_url='loginpage')
def techniqueform(request):
   form = TechniqueForm()
   if request.method == 'POST':
      form = TechniqueForm(request.POST, request.FILES, user=request.user)
      if form.is_valid():
         form.save()
         return redirect('techniquelibrary')
   else:
      form = TechniqueForm(user=request.user) 
   context = {'tform':form}
   return render(request, 'djangoApp/techniqueform.html', context)
   
@login_required(login_url='loginpage')
def updatejournal(request, pk):
   journalentry = TrainingLogEntry.objects.get(id=pk)
   form = JournalForm(instance=journalentry)
   if request.method== 'POST':
         form= JournalForm(request.POST, request.FILES, instance=journalentry)
         if form.is_valid():
            form.save()
            return redirect('trainingjournal')
   else:
      form = JournalForm(instance=journalentry, user=request.user)
   context={'jform':form}
   return render (request, 'djangoApp/journalform.html', context)

@login_required(login_url='loginpage')
def updatetechnique(request, pk):
   techniqueentry = TechniqueLibraryEntry.objects.get(id=pk)
   form = TechniqueForm(instance=techniqueentry)
   if request.method== 'POST':
         form= TechniqueForm(request.POST, request.FILES, instance=techniqueentry)
         if form.is_valid():
            form.save()
            return redirect('techniquelibrary')
   else: 
      form = TechniqueForm(instance=techniqueentry, user=request.user)
   context={'tform':form}
   return render (request, 'djangoApp/techniqueform.html', context)

def deletejournal(request, pk):
   journalentry = TrainingLogEntry.objects.get(id=pk)
   if request.method == 'POST':
      journalentry.delete()
      return redirect ('trainingjournal')
   context = {'journalentry': journalentry}
   return render (request, 'djangoApp/deletejournal.html', context)

def deletetechnique(request, pk):
   techniqueentry = TechniqueLibraryEntry.objects.get(id=pk)
   if request.method == 'POST':
      techniqueentry.delete()
      return redirect ('techniquelibrary')
   context = {'techniqueentry': techniqueentry}
   return render (request, 'djangoApp/deletetechnique.html', context)

@login_required(login_url='loginpage')
def techniqueseries(request):
    current_user = request.user
    series_entries_queryset = TechniqueSeriesEntry.objects.filter(user=current_user)
    tFilter = TechniqueSeriesFilter(request.GET, queryset=series_entries_queryset)

    context = {
        'series_entries': tFilter.qs,  # Use the filtered queryset here
        'tFilter': tFilter,
    }
    return render(request, 'djangoApp/techniqueseries.html', context)

@login_required(login_url='loginpage')
def techniqueseriesform(request):
    if request.method == 'POST':
        form = TechniqueSeriesForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            series_entry = form.save(commit=False)
            series_entry.user = request.user
            series_entry.save()

            # Extract and parse the ordered list of technique IDs
            techniques_order = request.POST.get('techniques_order', '')
            ordered_technique_ids = [int(tid) for tid in techniques_order.split(',') if tid.isdigit()]

            # Clear existing TechniqueSeriesLinking and re-create them in order
            TechniqueSeriesLinking.objects.filter(TechniqueSeriesEntry=series_entry).delete()
            for index, tech_id in enumerate(ordered_technique_ids, start=1):
                TechniqueSeriesLinking.objects.create(
                    TechniqueSeriesEntry=series_entry,
                    TechniqueLibraryEntry_id=tech_id,
                    order=index  
                )

            return redirect('techniqueseries')
    else:
        form = TechniqueSeriesForm(user=request.user)

    context = {'jform': form}
    return render(request, 'djangoApp/techniqueseriesform.html', context)

@login_required(login_url='loginpage')
def updatetechniqueseries(request, pk):
    series_entry = get_object_or_404(TechniqueSeriesEntry, id=pk, user=request.user)
    if request.method == 'POST':
        form = TechniqueSeriesForm(request.POST, request.FILES, instance=series_entry, user=request.user)
        if form.is_valid():
            saved_series_entry = form.save(commit=False)
            saved_series_entry.save()
            techniques_order = request.POST.get('techniques_order', '')
            ordered_technique_ids = [int(tid) for tid in techniques_order.split(',') if tid.isdigit()]

            TechniqueSeriesLinking.objects.filter(TechniqueSeriesEntry=saved_series_entry).delete()
            for index, tech_id in enumerate(ordered_technique_ids, start=1):
                TechniqueSeriesLinking.objects.create(
                    TechniqueSeriesEntry=saved_series_entry,
                    TechniqueLibraryEntry_id=tech_id,
                    order=index
                )

            return redirect('techniqueseries')
    else:
        form = TechniqueSeriesForm(instance=series_entry, user=request.user)

    context = {'jform': form}
    return render(request, 'djangoApp/techniqueseriesform.html', context)

@login_required(login_url='loginpage')
def deletetechniqueseries(request, pk):
    series_entry = TechniqueSeriesEntry.objects.get(id=pk, user=request.user)
    if request.method == 'POST':

djangoApp/templates/djangoApp/deletejournal.html
{% extends 'djangoApp/home.html' %}

{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class = "card card-body">
            
            <p style ="color:black;">Are you sure you want to delete "{{journalentry}}"?</p>
            <form action ="{% url 'deletejournal' journalentry.id %}" method="POST">

                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'trainingjournal' %}">Cancel</a>

                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>    

{% endblock %}

djangoApp/templates/djangoApp/deletetechnique.html
{% extends 'djangoApp/home.html' %}

{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class = "card card-body">
            <p style="color:black;">Are you sure you want to delete "{{techniqueentry}}"?</p>

            <form action ="{% url 'deletetechnique' techniqueentry.id %}" method="POST">

                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'techniquelibrary' %}">Cancel</a>

                <input class ="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>

{% endblock %}

djangoApp/templates/djangoApp/deletetechniqueseries.html
{% extends 'djangoApp/home.html' %}

{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class = "card card-body">
            
            <p style ="color:black;">Are you sure you want to delete "{{techniqueseriesentry}}"?</p>
            <form action ="{% url 'deletetechniqueseries' series_entry.id %}" method="POST">

                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'techniqueseries' %}">Cancel</a>

                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>    

{% endblock %}

djangoApp/templates/djangoApp/home.html
{% extends 'djangoApp/main.html' %}
{% load static %}
{% block content %}
<style>
    .maincontent{
        margin: 0 auto;
        max-width: 800px;
        padding: 20px;
        text-align: center;
    }
</style>

   <!-- MAIN IMAGE HOME  -->
   <div class="container-fluid black-background">
    <div class="row no-padding-margin">
        <div class="col-12 no-padding-margin position-relative">
            <img src="{% static 'djangoApp/images/home.JPG' %}" alt="Home Image" class="img-fluid w-100" role="img">
            <div class="overlay-content position-absolute top-50 start-50 translate-middle text-center">
                <h1 class="overlay-header text-white">Brazilian Jiu Jitsu Journal</h1>
            
                <h2 class="overlay-header text-white">Improve your game today!</h2>
                <br>
                <button aria-label="Join Now Button" class="btn btn-primary">Join Now</button>
            </div>
        </div>
    </div>
</div>

<!-- WELCOME SECTION / DESCRIPTION -->
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-8">
            <br>

            <h3 class="text-center">Welcome to</h3>
            <h2 class="text-center">Brazilian Jiu Jitsu Journal</h2>
            <p>The online platform created specifically for Brazilian Jiu Jitsu enthusiasts. Whether you're a
                seasoned practitioner, a dedicated coach, or simply someone looking to dive into the world of BJJ,
                we're here to support your journey. At BJJ Journal, we understand the importance of keeping track of
                your training progress. That's why we've developed an intuitive training log feature that allows you
                to record and organize your training sessions effortlessly. From drilling techniques to live
                sparring, you can document every step of your training and gain valuable insights into your
                development over time. But that's not all—our platform also provides a dedicated technique library
                where you can build your own collection of BJJ techniques. Whether it's a fundamental sweep, a
                sneaky submission, or a complex transition, you can store and categorize your favorite techniques in
                one place. With the ability to add detailed descriptions and even attach videos, you'll have a handy
                resource to refer to whenever you need it. Lastly, the ability to string techniques together into series that can 
            set you apart from the competition is an integral part of the learning process in BJJ. Your Technique Series page gives you a space
        to string together techniques from your technique library into series applicable in your live rolls. The possible combinations are endless!  </p>
        </div>
    </div>
</div>

<!-- TESTIMONIAL CAROUSEL -->
<div class="container-fluid grey-background">
    <div class="row justify-content-center">
        <div class="container-fluid">
            <br>
            <h2 class="text-center">Testimonials</h2>
            <br>
        </div>

        <div class="col-12 col-md-6">
            <div id="carouselExample" class="carousel slide" data-ride="carousel"
                aria-label="Testimonials Carousel">
                <!-- Tells you which slide you are on -->
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{% static 'djangoApp/images/Mary.jpg' %}" alt="Image of Mary J." role="img">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Mary J.</h5>
                                <p>"Positive review from Mary J.</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'djangoApp/images/Steph.jpg' %}" alt="Image of Steph J." role="img">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Steph J.</h5>
                                <p>"Positive review from Steph J.</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'djangoApp/images/Jim.jpg' %}" alt="Image of Jim P. and group" role="img">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Jim P.</h5>
                                <p>"Positive review from Jim P.</p>
                            </div>
                        </div>
                    </div>
                    <!-- left right buttons for carousel -->
                    <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev"
                        aria-label="previous button for carousel">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExample" role="button" data-slide=next
                        aria-label="next button for carousel">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>

    <!-- <div class = "maincontent">
        <h1>Welcome to BJJ Journal</h1>
        <p>The online platform created specifically for Brazilian Jiu Jitsu enthusiasts. Whether you're a seasoned practitioner, a dedicated coach, or simply someone looking to dive into the world of BJJ, we're here to support your journey.</p>
        <a href="{% url 'registerpage' %}" class="btn btn-primary">Join Today!</a>

        <h2>Record and Organize Your Training</h2>
        <p>At BJJ Journal, we understand the importance of keeping track of your training progress. That's why we've developed an intuitive training log feature that allows you to record and organize your training sessions effortlessly. From drilling techniques to live sparring, you can document every step of your training and gain valuable insights into your development over time.</p>
    
        <h2>Build Your Technique Library</h2>
        <p>But that's not all—our platform also provides a dedicated technique library where you can build your own collection of BJJ techniques. Whether it's a fundamental sweep, a sneaky submission, or a complex transition, you can store and categorize your favorite techniques in one place. With the ability to add detailed descriptions and even attach videos, you'll have a handy resource to refer to whenever you need it.</p>
    </div> -->

    {% endblock %}

djangoApp/templates/djangoApp/journalform.html
{% extends 'djangoApp/home.html' %}

{% block content %}
<style>
    body {
        background-color: rgb(210, 202, 202);
    }
</style>
            <form  action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{jform}}
            <input type = "submit" name="Submit">

            

{% endblock %}

djangoApp/templates/djangoApp/loginpage.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #605e5e !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #894848;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #821313 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #000000 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					
                    <h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		
                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'registerpage' %}" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						Return <a href="{% url 'home' %}" class="ml-2">Home</a>
					</div>
			</div>


		
			</div>
		</div>
	</div>
</body>

</html>

djangoApp/templates/djangoApp/techniqueform.html
{% extends 'djangoApp/home.html' %}

{% block content %}
<style>
    body {
        background-color: rgb(210, 202, 202);
    }
</style>

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{tform}}
            <input type = "submit" name="Submit">

          

{% endblock %}

djangoApp/templates/djangoApp/techniqueseries.html
{% extends 'djangoApp/main.html' %}

{% block content %}
<style>
    body {
        background-color: rgb(210, 202, 202);
    }
</style>

<div class="content-container">
    <br>
<div class="row">
    <div class="col-md-12">
        <h5>Your Series</h5>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- Button to toggle the visibility of the form -->
        <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#searchForm" aria-expanded="false" aria-controls="searchForm">
            Search
        </button>
        <div class="collapse" id="searchForm">
            <div class="card card-body">
                <form style="color:black" method="get">
        <div class="card card-body">
            <form style="color:black" method="get">
                {{ tFilter.form.as_p }}
                <button class="btn btn-secondary" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
    <hr>
        <div class="card card-body">
            <a class="btn btn-secondary btn-sm btn-block" href="{% url 'techniqueseriesform' %}">Create Series</a>
            <table class="table table-sm">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Techniques</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                
                {% for i in series_entries %}
                    <tr>
                        <td>{{ i.SeriesName }}</td>
                        <td>{{ i.Description }}</td>
                        <td>
                            <ul style="list-style-type:none; padding: 0;">
                                {% for link in i.techniqueserieslinking_set.all %}
                                    <li>{{ link.TechniqueLibraryEntry.Technique_Name }}</li>
                                {% empty %}
                                    <li>No techniques added.</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td><a class="btn btn-secondary btn-sm" href="{% url 'updatetechniqueseries' i.id %}">Update</a></td>
                        <td><a class="btn btn-danger btn-sm" href="{% url 'deletetechniqueseries' i.id %}">Remove</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
</div>
<br>


{% endblock %}

       